Repository AY1920S2-CS2103T-T10-4/main, pull requests merged in 2020-03, with the labels that each got.

#66 [v1.1] Changed photo
  docs/images/kester-ng.png
Labels: priority.Low

#73 [v1.1] Removed learning outcomes from readme
  README.adoc
Labels: priority.High

#74 [v1.1] Added Note model, along with its JUNIT test
  src/main/java/seedu/address/model/activity/Note.java
  src/test/java/seedu/address/model/activity/NoteTest.java
Labels: priority.High, type.Task

#80 [v1.2] Added the base models from master and fixed checkstyle errors
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/activity/Date.java
  src/main/java/seedu/address/model/activity/Name.java
  src/main/java/seedu/address/model/activity/Priority.java
  src/test/java/seedu/address/model/activity/DateTest.java
  src/test/java/seedu/address/model/activity/NameTest.java
  src/test/java/seedu/address/model/activity/PriorityTest.java
Labels: priority.High

#84 [v1.2] Updated CLI Syntax and ParserUtil
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Story, type.Task

#89 [v1.2] Update Activity.java, UniqueActivityList.java, NasaBook.java and test. Added draft Deadline, Event, Lesson needed for testing.
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/NasaBook.java
  src/main/java/seedu/address/model/ReadOnlyNasaBook.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/activity/Deadline.java
  src/main/java/seedu/address/model/activity/Event.java
  src/main/java/seedu/address/model/activity/Lesson.java
  src/main/java/seedu/address/model/activity/TaskName.java
  src/main/java/seedu/address/model/activity/UniqueActivityList.java
  src/main/java/seedu/address/model/activity/exceptions/ActivityNotFoundException.java
  src/main/java/seedu/address/model/activity/exceptions/DuplicateActivityException.java
  src/test/java/seedu/address/model/activity/UniqueActivityListTest.java
  src/test/java/seedu/address/testutil/ActivityBuilder.java
  src/test/java/seedu/address/testutil/TypicalActivities.java
Labels: priority.High, status.Ongoing

#92 Implement module class
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/test/java/seedu/address/model/module/ModuleCodeTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
Labels: priority.High, status.Ongoing

#90 [v1.2] Refactoring
  src/main/java/NASA/AppParameters.java
  src/main/java/NASA/Main.java
  src/main/java/NASA/MainApp.java
  src/main/java/NASA/commons/core/Config.java
  src/main/java/NASA/commons/core/GuiSettings.java
  src/main/java/NASA/commons/core/LogsCenter.java
  src/main/java/NASA/commons/core/Messages.java
  src/main/java/NASA/commons/core/Version.java
  src/main/java/NASA/commons/core/index/Index.java
  src/main/java/NASA/commons/exceptions/DataConversionException.java
  src/main/java/NASA/commons/exceptions/IllegalValueException.java
  src/main/java/NASA/commons/util/AppUtil.java
  src/main/java/NASA/commons/util/CollectionUtil.java
  src/main/java/NASA/commons/util/ConfigUtil.java
  src/main/java/NASA/commons/util/FileUtil.java
  src/main/java/NASA/commons/util/JsonUtil.java
  src/main/java/NASA/commons/util/StringUtil.java
  src/main/java/NASA/logic/commands/Command.java
  src/main/java/NASA/logic/commands/CommandResult.java
  src/main/java/NASA/logic/commands/ExitCommand.java
  src/main/java/NASA/logic/commands/HelpCommand.java
  src/main/java/NASA/logic/commands/exceptions/CommandException.java
  src/main/java/NASA/logic/parser/ArgumentMultimap.java
  src/main/java/NASA/logic/parser/ArgumentTokenizer.java
  src/main/java/NASA/logic/parser/CliSyntax.java
  src/main/java/NASA/logic/parser/Parser.java
  src/main/java/NASA/logic/parser/ParserUtil.java
  src/main/java/NASA/logic/parser/Prefix.java
  src/main/java/NASA/logic/parser/exceptions/ParseException.java
  src/main/java/NASA/model/NasaBook.java
  src/main/java/NASA/model/ReadOnlyNasaBook.java
  src/main/java/NASA/model/ReadOnlyUserPrefs.java
  src/main/java/NASA/model/UserPrefs.java
  src/main/java/NASA/model/activity/Activity.java
  src/main/java/NASA/model/activity/Date.java
  src/main/java/NASA/model/activity/Deadline.java
  src/main/java/NASA/model/activity/Event.java
  src/main/java/NASA/model/activity/Lesson.java
  src/main/java/NASA/model/activity/Name.java
  src/main/java/NASA/model/activity/Note.java
  src/main/java/NASA/model/activity/Priority.java
  src/main/java/NASA/model/activity/TaskName.java
  src/main/java/NASA/model/activity/UniqueActivityList.java
  src/main/java/NASA/model/activity/exceptions/ActivityNotFoundException.java
  src/main/java/NASA/model/activity/exceptions/DuplicateActivityException.java
  src/main/java/NASA/model/module/Module.java
  src/main/java/NASA/model/module/ModuleCode.java
  src/test/java/NASA/AppParametersTest.java
  src/test/java/NASA/model/activity/DateTest.java
  src/test/java/NASA/model/activity/NameTest.java
  src/test/java/NASA/model/activity/NoteTest.java
  src/test/java/NASA/model/activity/PriorityTest.java
  src/test/java/NASA/model/activity/UniqueActivityListTest.java
  src/test/java/NASA/model/module/ModuleCodeTest.java
  src/test/java/NASA/model/module/ModuleTest.java
  src/test/java/NASA/testutil/ActivityBuilder.java
  src/test/java/NASA/testutil/Assert.java
  src/test/java/NASA/testutil/TypicalActivities.java
  src/test/java/NASA/testutil/TypicalIndexes.java
Labels: priority.High

#94 [v1.2] Adding commands and their parsers (Incomplete)
  src/main/java/NASA/logic/commands/AddModuleCommand.java
  src/main/java/NASA/logic/commands/DeleteActivityCommand.java
  src/main/java/NASA/logic/commands/DeleteModuleCommand.java
  src/main/java/NASA/logic/commands/EditActivityCommand.java
  src/main/java/NASA/logic/commands/EditModuleCommand.java
  src/main/java/NASA/logic/commands/FindCommand.java
  src/main/java/NASA/logic/commands/ListCommand.java
  src/main/java/NASA/logic/commands/addcommands/AddCommand.java
  src/main/java/NASA/logic/commands/addcommands/AddDeadlineCommand.java
  src/main/java/NASA/logic/commands/addcommands/AddEventCommand.java
  src/main/java/NASA/logic/commands/addcommands/AddLessonCommand.java
  src/main/java/NASA/logic/parser/CliSyntax.java
  src/main/java/NASA/logic/parser/DeleteActivityCommandParser.java
  src/main/java/NASA/logic/parser/FindCommandParser.java
  src/main/java/NASA/logic/parser/ParserUtil.java
  src/main/java/NASA/logic/parser/addcommandparser/AddCommandParser.java
  src/main/java/NASA/logic/parser/addcommandparser/AddDeadlineCommandParser.java
  src/main/java/NASA/logic/parser/addcommandparser/AddEventCommandParser.java
  src/main/java/NASA/logic/parser/addcommandparser/AddLessonCommandParser.java
  src/main/java/NASA/model/Model.java
  src/main/java/NASA/model/ModelManager.java
Labels: priority.High, type.Task

#93 [v1.2] Modified NasaBook, ModelManagerNasa, ModelNasa, ReadOnlyNasaBook, UserPrefsNasa
  src/main/java/NASA/model/ModelManagerNasa.java
  src/main/java/NASA/model/ModelNasa.java
  src/main/java/NASA/model/NasaBook.java
  src/main/java/NASA/model/ReadOnlyNasaBook.java
  src/main/java/NASA/model/ReadOnlyUserPrefsNasa.java
  src/main/java/NASA/model/UserPrefsNasa.java
  src/main/java/NASA/model/activity/Activity.java
  src/main/java/NASA/model/activity/Date.java
  src/main/java/NASA/model/activity/Deadline.java
  src/main/java/NASA/model/activity/Status.java
  src/main/java/NASA/model/module/Module.java
  src/main/java/NASA/model/module/UniqueModuleList.java
  src/main/java/NASA/model/module/exceptions/DuplicateModuleException.java
  src/main/java/NASA/model/module/exceptions/ModuleNotFoundException.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/NasaBook.java
  src/main/java/seedu/address/model/ReadOnlyNasaBook.java
  src/main/java/seedu/address/model/activity/Activity.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/module/exceptions/DuplicateModuleException.java
  src/main/java/seedu/address/model/module/exceptions/ModuleNotFoundException.java
Labels: priority.High, status.Ongoing, type.Task

#96 [v1.2] Updated LocalDate to LocalDateTime
  src/main/java/NASA/model/activity/Activity.java
  src/main/java/NASA/model/activity/Date.java
  src/test/java/NASA/logic/parser/ParserUtilTest.java
  src/test/java/NASA/model/activity/DateTest.java
Labels: priority.High, severity.High, type.Bug

#99 [V1.2] Added moduleName and AddModuleCommandParser
  src/main/java/NASA/logic/commands/AddModuleCommand.java
  src/main/java/NASA/logic/parser/AddModuleCommandParser.java
  src/main/java/NASA/logic/parser/ParserUtil.java
  src/main/java/NASA/model/module/Module.java
  src/main/java/NASA/model/module/ModuleName.java
  src/test/java/NASA/logic/parser/ParserUtilTest.java
  src/test/java/NASA/model/activity/NameTest.java
  src/test/java/NASA/model/module/ModuleNameTest.java
Labels: priority.High, type.Enhancement, type.Task

#103 Add helper methods for lesson to regenerate after the lesson is over, and Regenerable interface
  src/main/java/NASA/model/Regenerable.java
  src/main/java/NASA/model/activity/Activity.java
  src/main/java/NASA/model/activity/Date.java
  src/main/java/NASA/model/activity/Deadline.java
  src/main/java/NASA/model/activity/Event.java
  src/main/java/NASA/model/activity/Lesson.java
  src/test/java/NASA/testutil/ActivityBuilder.java
Labels: priority.High, status.Ongoing, type.Task

#100 [v1.2] Logic of commands (DO NOT MERGE)
  Test Results - AddCommandParserTest.html
  build.gradle
  src/main/java/nasa/logic/commands/AddModuleCommand.java
  src/main/java/nasa/logic/commands/DeleteActivityCommand.java
  src/main/java/nasa/logic/commands/DeleteModuleCommand.java
  src/main/java/nasa/logic/commands/EditActivityCommand.java
  src/main/java/nasa/logic/commands/EditModuleCommand.java
  src/main/java/nasa/logic/commands/ListCommand.java
  src/main/java/nasa/logic/commands/addcommands/AddCommand.java
  src/main/java/nasa/logic/commands/addcommands/AddDeadlineCommand.java
  src/main/java/nasa/logic/commands/addcommands/AddEventCommand.java
  src/main/java/nasa/logic/commands/addcommands/AddLessonCommand.java
  src/main/java/nasa/logic/parser/AddModuleCommandParser.java
  src/main/java/nasa/logic/parser/DeleteActivityCommandParser.java
  src/main/java/nasa/logic/parser/DeleteModuleCommandParser.java
  src/main/java/nasa/logic/parser/EditActivityCommandParser.java
  src/main/java/nasa/logic/parser/EditModuleCommandParser.java
  src/main/java/nasa/logic/parser/FindCommandParser.java
  src/main/java/nasa/logic/parser/NasaBookParser.java
  src/main/java/nasa/logic/parser/ParserUtil.java
  src/main/java/nasa/logic/parser/addcommandparser/AddCommandParser.java
  src/main/java/nasa/logic/parser/addcommandparser/AddDeadlineCommandParser.java
  src/main/java/nasa/logic/parser/addcommandparser/AddEventCommandParser.java
  src/main/java/nasa/logic/parser/addcommandparser/AddLessonCommandParser.java
  src/main/java/nasa/model/NasaBook.java
  src/main/java/nasa/model/activity/Activity.java
  src/main/java/nasa/model/activity/Deadline.java
  src/test/java/nasa/logic/commands/AddModuleCommandTest.java
  src/test/java/nasa/logic/commands/CommandResultTest.java
  src/test/java/nasa/logic/commands/CommandTestUtil.java
  src/test/java/nasa/logic/commands/ExitCommandTest.java
  src/test/java/nasa/logic/commands/HelpCommandTest.java
  src/test/java/nasa/logic/commands/addcommands/AddDeadlineCommandTest.java
  src/test/java/nasa/logic/parser/AddModuleCommandParserTest.java
  src/test/java/nasa/logic/parser/CommandParserTestUtil.java
  src/test/java/nasa/logic/parser/DeleteActivityCommandParserTest.java
  src/test/java/nasa/logic/parser/DeleteModuleCommandParserTest.java
  src/test/java/nasa/logic/parser/addcommandparser/AddDeadlineCommandParserTest.java
Labels: priority.High, status.Ongoing

#115 [v1.2] Completed storage functionality and basic UI
  src/main/java/NASA/commons/util/AppUtil.java
  src/main/java/NASA/logic/commands/CommandResult.java
  src/main/java/NASA/model/activity/Event.java
  src/main/java/NASA/model/activity/Note.java
  src/main/java/nasa/commons/core/GuiSettings.java
  src/main/java/nasa/logic/commands/addcommands/AddDeadlineCommand.java
  src/main/java/nasa/logic/commands/addcommands/AddEventCommand.java
  src/main/java/nasa/logic/commands/addcommands/AddLessonCommand.java
  src/main/java/nasa/logic/parser/addcommandparser/AddEventCommandParser.java
  src/main/java/nasa/logic/parser/addcommandparser/AddLessonCommandParser.java
  src/main/java/nasa/model/activity/Activity.java
  src/main/java/nasa/storage/JsonAdaptedActivity.java
  src/main/java/nasa/storage/RuntimeTypeAdapterFactory.java
  src/main/java/nasa/ui/ActivityCard.java
  src/main/java/nasa/ui/ActivityListPanel.java
  src/main/java/nasa/ui/MainWindow.java
  src/main/java/nasa/ui/ModuleCard.java
  src/main/java/nasa/ui/ModuleListPanel.java
  src/main/resources/view/ActivityListCard.fxml
  src/main/resources/view/ActivityListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
Labels: priority.High

#114 [v1.3] Adding JUNIT tests and fixing checkstyle errors (DO NOT MERGE)
  src/main/java/nasa/commons/core/Messages.java
  src/main/java/nasa/logic/commands/FindCommand.java
  src/main/java/nasa/logic/commands/ListCommand.java
  src/main/java/nasa/logic/parser/FindCommandParser.java
  src/main/java/nasa/model/Model.java
  src/main/java/nasa/model/ModelManager.java
  src/test/java/nasa/logic/commands/DeleteActivityCommandTest.java
  src/test/java/nasa/logic/commands/FindCommandTest.java
  src/test/java/nasa/logic/parser/FindCommandParserTest.java
Labels: priority.High, status.Ongoing, type.Task

#132 Fixed modulecode and activity name being case sensitive
  src/main/java/nasa/model/activity/Name.java
  src/main/java/nasa/model/activity/UniqueActivityList.java
  src/main/java/nasa/model/module/ModuleCode.java
Labels: priority.High, type.Bug

#136 Updated Developer Docs
  docs/DeveloperGuide.adoc
  docs/diagrams/AddDeadlineActivityDiagram.puml
  docs/diagrams/AddDeadlineLogicSequenceDiagram.puml
  docs/images/AddDeadlineActivityDiagram.png
  docs/images/AddDeadlineLogicSequenceDiagram.png
Labels: priority.High, type.Task

#143 Updated UG with Reminders feature + Test cases
  docs/DeveloperGuide.adoc
  docs/diagrams/AddReminderActivityDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/SnoozeReminderActivityDiagram.puml
  docs/images/AddReminderActivityDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/SnoozeReminderActivityDiagram.png
Labels: priority.High, type.Task

#146 Fixed errors where module cannot be found for certain commands
  src/main/java/nasa/logic/commands/DeleteActivityCommand.java
  src/main/java/nasa/logic/commands/addcommands/AddCommand.java
  src/test/java/nasa/logic/commands/DeleteActivityCommandTest.java
Labels: priority.High, type.Bug

#113 Add EditModuleCommand and EditActivityCommand class and tests.
  docs/UserGuide.adoc
  src/main/java/nasa/commons/core/Messages.java
  src/main/java/nasa/logic/commands/EditActivityCommand.java
  src/main/java/nasa/logic/commands/EditModuleCommand.java
  src/main/java/nasa/logic/parser/ArgumentMultimap.java
  src/main/java/nasa/logic/parser/EditActivityCommandParser.java
  src/main/java/nasa/logic/parser/EditModuleCommandParser.java
  src/main/java/nasa/logic/parser/ParserUtil.java
  src/main/java/nasa/model/Model.java
  src/main/java/nasa/model/ModelManager.java
  src/main/java/nasa/model/NasaBook.java
  src/main/java/nasa/model/ReadOnlyNasaBook.java
  src/main/java/nasa/model/activity/Activity.java
  src/main/java/nasa/model/activity/Deadline.java
  src/main/java/nasa/model/activity/Priority.java
  src/main/java/nasa/model/module/Module.java
  src/main/java/nasa/model/module/UniqueModuleList.java
  src/main/java/nasa/model/util/SampleDataUtil.java
  src/main/java/nasa/storage/JsonAdaptedActivity.java
  src/main/java/nasa/ui/MainWindow.java
  src/test/java/nasa/logic/commands/AddCommandTest.java
  src/test/java/nasa/logic/commands/CommandTestUtil.java
  src/test/java/nasa/logic/commands/EditActivityCommandTest.java
  src/test/java/nasa/logic/commands/EditActivityDescriptorTest.java
  src/test/java/nasa/logic/commands/EditModuleCommandTest.java
  src/test/java/nasa/logic/commands/EditModuleDescriptorTest.java
  src/test/java/nasa/logic/commands/FindCommandTest.java
  src/test/java/nasa/logic/parser/EditActivityCommandParserTest.java
  src/test/java/nasa/logic/parser/EditModuleCommandParserTest.java
  src/test/java/nasa/logic/parser/addcommandparser/AddDeadlineCommandParserTest.java
  src/test/java/nasa/logic/parser/addcommandparser/AddEventCommandParserTest.java
  src/test/java/nasa/logic/parser/addcommandparser/AddLessonCommandParserTest.java
  src/test/java/nasa/model/ModelManagerTest.java
  src/test/java/nasa/model/NasaBookTest.java
  src/test/java/nasa/model/activity/DeadlineTest.java
  src/test/java/nasa/testutil/DeadlineBuilder.java
  src/test/java/nasa/testutil/EditActivityDescriptorBuilder.java
  src/test/java/nasa/testutil/EditModuleDescriptorBuilder.java
  src/test/java/nasa/testutil/NasaBookBuilder.java
Labels: priority.High, status.Ongoing, type.Task

#150 Sort feature (WIP)
  docs/DeveloperGuide.adoc
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortLogicSequenceDiagram.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortLogicSequenceDiagram.png
Labels: priority.High, status.Ongoing, type.Enhancement
