Repository AY1920S2-CS2103T-T10-4/main, pull requests merged in 2020-04, with the labels that each got.

#155 Calendar View for activity list (Done)
  docs/UserGuide.adoc
  docs/images/AddReminderClassDiagram.png
  src/main/java/NASA/model/activity/Event.java
  src/main/java/NASA/ui/CalendarView.java
  src/main/java/nasa/model/ModelManager.java
  src/main/java/nasa/model/activity/Activity.java
  src/main/java/nasa/model/activity/Deadline.java
  src/main/java/nasa/model/activity/Lesson.java
  src/main/java/nasa/ui/MainWindow.java
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Story

#163 [Bug] Users could enter invalid event, deadlines and lessons
  src/main/java/NASA/model/activity/Event.java
  src/main/java/nasa/logic/parser/addcommandparser/AddDeadlineCommandParser.java
  src/main/java/nasa/logic/parser/addcommandparser/AddEventCommandParser.java
  src/main/java/nasa/logic/parser/addcommandparser/AddLessonCommandParser.java
  src/main/java/nasa/model/activity/Lesson.java
Labels: priority.High, severity.High, type.Bug

#160 [v1.3] Added keyboard shortcuts, tab and minor enhancements to UI and basic statistic classes.
  src/main/java/NASA/logic/commands/StatisticsCommand.java
  src/main/java/NASA/logic/parser/StatisticsCommandParser.java
  src/main/java/NASA/ui/CalendarView.java
  src/main/java/NASA/ui/StatisticsPanel.java
  src/main/java/NASA/ui/TabPanel.java
  src/main/java/NASA/ui/activity/ActivityCard.java
  src/main/java/NASA/ui/activity/ActivityListPanel.java
  src/main/java/nasa/logic/commands/DeleteActivityCommand.java
  src/main/java/nasa/logic/commands/EditModuleCommand.java
  src/main/java/nasa/logic/parser/NasaBookParser.java
  src/main/java/nasa/model/activity/Date.java
  src/main/java/nasa/model/module/ModuleCode.java
  src/main/java/nasa/model/module/ModuleName.java
  src/main/java/nasa/ui/CommandBox.java
  src/main/java/nasa/ui/MainWindow.java
  src/main/java/nasa/ui/ModuleCard.java
  src/main/java/nasa/ui/ModuleListPanel.java
  src/main/resources/view/ActivityListCard.fxml
  src/main/resources/view/ActivityListPanel.fxml
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/NasaMainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatisticsPanel.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TabPanel.fxml
Labels: priority.High, status.Ongoing, type.Enhancement

#159 Sort impl
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/nasa/commons/util/AppUtil.java
  src/main/java/nasa/logic/commands/CommandResult.java
  src/main/java/nasa/logic/commands/RedoCommand.java
  src/main/java/nasa/logic/commands/RepeatCommand.java
  src/main/java/nasa/logic/commands/SortCommand.java
  src/main/java/nasa/logic/commands/StatisticsCommand.java
  src/main/java/nasa/logic/commands/UndoCommand.java
  src/main/java/nasa/logic/parser/CliSyntax.java
  src/main/java/nasa/logic/parser/NasaBookParser.java
  src/main/java/nasa/logic/parser/ParserUtil.java
  src/main/java/nasa/logic/parser/RepeatActivityCommandParser.java
  src/main/java/nasa/logic/parser/SortCommandParser.java
  src/main/java/nasa/logic/parser/StatisticsCommandParser.java
  src/main/java/nasa/model/HistoryBook.java
  src/main/java/nasa/model/HistoryManager.java
  src/main/java/nasa/model/HistoryModel.java
  src/main/java/nasa/model/Model.java
  src/main/java/nasa/model/ModelManager.java
  src/main/java/nasa/model/ReadOnlyHistory.java
  src/main/java/nasa/model/activity/Event.java
  src/main/java/nasa/model/activity/Note.java
  src/main/java/nasa/model/activity/Schedule.java
  src/main/java/nasa/model/history/History.java
  src/main/java/nasa/model/history/ModuleListHistory.java
  src/main/java/nasa/model/module/Module.java
  src/main/java/nasa/model/module/SortMethod.java
  src/main/java/nasa/model/module/UniqueModuleList.java
  src/main/java/nasa/storage/JsonAdaptedHistory.java
  src/main/java/nasa/ui/CalendarView.java
  src/main/java/nasa/ui/StatisticsPanel.java
  src/main/java/nasa/ui/TabPanel.java
  src/main/java/nasa/ui/activity/ActivityCard.java
  src/main/java/nasa/ui/activity/ActivityListPanel.java
  src/test/java/nasa/logic/commands/AddCommandTest.java
Labels: priority.High, status.Ongoing, type.Enhancement

#166 Update Ui.png
  docs/images/Ui.png
Labels: type.Story

#168 Updated User guide
  README.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: priority.High

#173 Update User Guide with Calendar styling
  docs/ContactUs.adoc
  docs/UserGuide.adoc
  src/main/java/nasa/ui/CalendarView.java
  src/main/java/nasa/ui/StatisticsPanel.java
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TabPanel.fxml
Labels: priority.High

#177 Sort order update
  docs/UserGuide.adoc
  src/main/java/nasa/model/module/SortMethod.java
Labels: priority.High

#179 [v1.4] Update UI to fit activity type and implement statistics functionality
  docs/UserGuide.adoc
  src/main/java/nasa/commons/core/index/Index.java
  src/main/java/nasa/logic/commands/CommandResult.java
  src/main/java/nasa/logic/commands/DeleteActivityCommand.java
  src/main/java/nasa/logic/commands/DoneCommand.java
  src/main/java/nasa/logic/commands/EditActivityCommand.java
  src/main/java/nasa/logic/commands/ExitCommand.java
  src/main/java/nasa/logic/commands/FindCommand.java
  src/main/java/nasa/logic/commands/HelpCommand.java
  src/main/java/nasa/logic/commands/QuoteCommand.java
  src/main/java/nasa/logic/commands/RedoCommand.java
  src/main/java/nasa/logic/commands/RepeatCommand.java
  src/main/java/nasa/logic/commands/StatisticsCommand.java
  src/main/java/nasa/logic/commands/UndoCommand.java
  src/main/java/nasa/logic/parser/CliSyntax.java
  src/main/java/nasa/logic/parser/ParserUtil.java
  src/main/java/nasa/logic/parser/StatisticsCommandParser.java
  src/main/java/nasa/ui/MainWindow.java
  src/main/java/nasa/ui/StatisticsPanel.java
  src/main/java/nasa/ui/TabPanel.java
  src/main/java/nasa/ui/activity/ActivityListPanel.java
  src/main/java/nasa/ui/activity/DeadlineCard.java
  src/main/java/nasa/ui/activity/EventCard.java
  src/main/java/nasa/ui/activity/LessonCard.java
  src/main/resources/view/ActivityListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DeadlineCard.fxml
  src/main/resources/view/EventCard.fxml
  src/main/resources/view/LessonCard.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/StatisticsPanel.fxml
  src/test/java/nasa/logic/commands/CommandResultTest.java
  src/test/java/nasa/logic/commands/ExitCommandTest.java
  src/test/java/nasa/logic/commands/HelpCommandTest.java
Labels: priority.High, status.Ongoing, type.Enhancement, type.Task

#240 [V1.4] Fixed adding activity documentation and calendar command
  docs/UserGuide.adoc
  docs/images/calendar.png
Labels: severity.VeryLow, type.Bug

#241 [V1.4] Added extension of calendar feature
  src/main/java/nasa/ui/CalendarView.java
  src/main/resources/view/CalendarView.fxml
Labels: priority.Medium, type.Enhancement

#256 Updated Calendar, fixed bugs and logic/model tests passed.
  src/main/java/nasa/logic/commands/DeleteDeadlineCommand.java
  src/main/java/nasa/logic/commands/DeleteEventCommand.java
  src/main/java/nasa/logic/commands/DeleteModuleCommand.java
  src/main/java/nasa/logic/commands/EditDeadlineCommand.java
  src/main/java/nasa/logic/commands/EditEventCommand.java
  src/main/java/nasa/logic/commands/FindCommand.java
  src/main/java/nasa/logic/commands/ListCommand.java
  src/main/java/nasa/logic/commands/addcommands/AddEventCommand.java
  src/main/java/nasa/logic/commands/addcommands/AddLessonCommand.java
  src/main/java/nasa/logic/parser/FindCommandParser.java
  src/main/java/nasa/logic/parser/ListCommandParser.java
  src/main/java/nasa/logic/parser/NasaBookParser.java
  src/main/java/nasa/logic/parser/StatisticsCommandParser.java
  src/main/java/nasa/logic/parser/addcommandparser/AddEventCommandParser.java
  src/main/java/nasa/logic/parser/addcommandparser/AddLessonCommandParser.java
  src/main/java/nasa/model/activity/Date.java
  src/main/java/nasa/model/activity/Deadline.java
  src/main/java/nasa/model/activity/Event.java
  src/main/java/nasa/model/activity/Lesson.java
  src/main/java/nasa/ui/CalendarView.java
  src/test/java/nasa/logic/commands/AddCommandTest.java
  src/test/java/nasa/logic/commands/CommandTestUtil.java
  src/test/java/nasa/logic/commands/ContinueCommandTest.java
  src/test/java/nasa/logic/commands/DeleteActivityCommandTest.java
  src/test/java/nasa/logic/commands/DeleteModuleCommandTest.java
  src/test/java/nasa/logic/commands/DoneCommandTest.java
  src/test/java/nasa/logic/commands/EditActivityCommandTest.java
  src/test/java/nasa/logic/commands/EditActivityDescriptorTest.java
  src/test/java/nasa/logic/commands/FindCommandTest.java
  src/test/java/nasa/logic/commands/ListCommandTest.java
  src/test/java/nasa/logic/commands/UndoCommandTest.java
  src/test/java/nasa/logic/commands/addcommands/AddDeadlineCommandTest.java
  src/test/java/nasa/logic/commands/addcommands/AddEventCommandTest.java
  src/test/java/nasa/logic/commands/addcommands/AddLessonCommandTest.java
  src/test/java/nasa/logic/parser/EditActivityCommandParserTest.java
  src/test/java/nasa/logic/parser/addcommandparser/AddDeadlineCommandParserTest.java
  src/test/java/nasa/logic/parser/addcommandparser/AddEventCommandParserTest.java
  src/test/java/nasa/logic/parser/addcommandparser/AddLessonCommandParserTest.java
  src/test/java/nasa/model/ModelManagerTest.java
  src/test/java/nasa/model/NasaBookTest.java
  src/test/java/nasa/model/activity/DateTest.java
  src/test/java/nasa/model/activity/DeadlineTest.java
  src/test/java/nasa/model/activity/EventTest.java
  src/test/java/nasa/model/module/ModuleTest.java
  src/test/java/nasa/model/module/UniqueModuleListTest.java
  src/test/java/nasa/testutil/EditActivityDescriptorBuilder.java
  src/test/java/nasa/testutil/EventBuilder.java
  src/test/java/nasa/testutil/LessonBuilder.java
  src/test/java/nasa/testutil/ModuleBuilder.java
  src/test/java/nasa/testutil/TypicalActivities.java
  src/test/java/nasa/testutil/TypicalModules.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement, type.Story

#262 [v1.4] Fix event constructor bug
  src/main/java/nasa/model/activity/Event.java
Labels: priority.High

#263 Add qr code export functionality, currently export module code and mo…
  build.gradle
  docs/UserGuide.adoc
  src/main/java/nasa/commons/util/StringUtil.java
  src/main/java/nasa/logic/commands/CommandResult.java
  src/main/java/nasa/logic/commands/EditDeadlineCommand.java
  src/main/java/nasa/logic/commands/EditEventCommand.java
  src/main/java/nasa/logic/commands/EditModuleCommand.java
  src/main/java/nasa/logic/commands/ExitCommand.java
  src/main/java/nasa/logic/commands/ExportQrCommand.java
  src/main/java/nasa/logic/commands/HelpCommand.java
  src/main/java/nasa/logic/commands/SortCommand.java
  src/main/java/nasa/logic/commands/StatisticsCommand.java
  src/main/java/nasa/logic/parser/EditDeadlineCommandParser.java
  src/main/java/nasa/logic/parser/EditEventCommandParser.java
  src/main/java/nasa/logic/parser/EditModuleCommandParser.java
  src/main/java/nasa/logic/parser/NasaBookParser.java
  src/main/java/nasa/model/ModelManager.java
  src/main/java/nasa/model/activity/Activity.java
  src/main/java/nasa/model/activity/Event.java
  src/main/java/nasa/model/module/Module.java
  src/main/java/nasa/model/module/SortMethod.java
  src/main/java/nasa/ui/ExportQrWindow.java
  src/main/java/nasa/ui/MainWindow.java
  src/main/resources/view/ExportQrWindow.fxml
  src/test/java/nasa/logic/commands/CommandResultTest.java
  src/test/java/nasa/logic/commands/ExitCommandTest.java
  src/test/java/nasa/logic/commands/HelpCommandTest.java
Labels: status.Ongoing, type.Enhancement, type.Story

#269 Doc
  docs/UserGuide.adoc
  src/main/java/nasa/logic/commands/EditModuleCommand.java
Labels: type.Bug

#264 [v1.4] Added export calendar view to ics format
  src/main/java/nasa/logic/calendar/IcsCalendar.java
  src/main/java/nasa/logic/calendar/IcsDeadline.java
  src/main/java/nasa/logic/calendar/IcsEvent.java
  src/main/java/nasa/logic/calendar/IcsSchedule.java
  src/main/java/nasa/logic/commands/ExportCalendarCommand.java
  src/main/java/nasa/logic/parser/CliSyntax.java
  src/main/java/nasa/logic/parser/ExportCalendarCommandParser.java
  src/main/java/nasa/logic/parser/NasaBookParser.java
  src/main/java/nasa/logic/parser/ParserUtil.java
  src/main/java/nasa/model/ReadOnlyUserPrefs.java
  src/main/java/nasa/model/UserPrefs.java
  src/main/java/nasa/model/activity/Deadline.java
  src/main/java/nasa/model/activity/Event.java
  src/main/java/nasa/model/activity/Name.java
  src/main/java/nasa/ui/CalendarView.java
  src/test/java/nasa/logic/commands/ExportCalendarCommandTest.java
  src/test/java/nasa/logic/parser/ExportCalendarCommandParserTest.java
  src/test/java/nasa/model/activity/NameTest.java
Labels: priority.High, type.Enhancement, type.Story, type.Task

#272 [v1.4] Resized calendar and updated styling to make it look nicer
  src/main/java/nasa/model/module/ModuleName.java
  src/main/java/nasa/ui/CalendarView.java
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/TabPanel.fxml
Labels: priority.High

#273 [V1.4] Update docs
  docs/UserGuide.adoc
  docs/diagrams/AddDeadlineActivityDiagram.puml
  docs/diagrams/AddReminderActivityDiagram.puml
  docs/images/AddDeadlineActivityDiagram.png
  docs/images/AddReminderActivityDiagram.png
  docs/team/kester-ng.adoc
Labels: priority.High, type.Task

#275 [V1.4] Fix ics export
  src/main/java/nasa/logic/calendar/IcsDeadline.java
  src/main/java/nasa/logic/calendar/IcsSchedule.java
Labels: priority.High

#274 Fix bug with date issues
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/nasa/logic/commands/EditDeadlineCommand.java
  src/main/java/nasa/logic/commands/EditEventCommand.java
  src/main/java/nasa/model/ModelManager.java
  src/main/java/nasa/model/activity/Deadline.java
  src/main/java/nasa/model/activity/Event.java
Labels: type.Bug

#281 Added Hint Function
  src/main/java/nasa/logic/commands/CommandHint.java
  src/main/java/nasa/logic/commands/ListCommand.java
  src/main/java/nasa/logic/parser/ContinueCommandParser.java
  src/main/java/nasa/logic/parser/DeleteDeadlineCommandParser.java
  src/main/java/nasa/logic/parser/DeleteEventCommandParser.java
  src/main/java/nasa/logic/parser/DoneCommandParser.java
  src/main/java/nasa/logic/parser/EditDeadlineCommandParser.java
  src/main/java/nasa/logic/parser/EditEventCommandParser.java
  src/main/java/nasa/logic/parser/FindCommandParser.java
  src/main/java/nasa/logic/parser/RepeatDeadlineCommandParser.java
  src/main/java/nasa/logic/parser/RepeatEventCommandParser.java
  src/main/java/nasa/logic/parser/SortCommandParser.java
  src/main/java/nasa/logic/parser/addcommandparser/AddDeadlineCommandParser.java
  src/main/java/nasa/model/activity/Event.java
  src/main/java/nasa/ui/CalendarView.java
  src/main/java/nasa/ui/CommandBox.java
  src/main/java/nasa/ui/HelpWindow.java
  src/main/java/nasa/ui/HintWindow.java
  src/main/java/nasa/ui/MainWindow.java
  src/main/java/nasa/ui/ModuleCard.java
  src/main/java/nasa/ui/ModuleListPanel.java
  src/main/java/nasa/ui/activity/DeadlineCard.java
  src/main/java/nasa/ui/activity/DeadlineListPanel.java
  src/main/java/nasa/ui/activity/EventListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DeadlineCard.fxml
  src/main/resources/view/HintWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/test/java/nasa/logic/parser/ContinueCommandParserTest.java
  src/test/java/nasa/logic/parser/DoneCommandParserTest.java
  src/test/java/nasa/logic/parser/FindCommandParserTest.java
  src/test/java/nasa/logic/parser/addcommandparser/AddDeadlineCommandParserTest.java
Labels: type.Enhancement

#285 [v1.4] Added refresh command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddDeadlineLogicSequenceDiagram.puml
  docs/diagrams/AddDeadlineModelSequenceDiagram.puml
  docs/diagrams/ExportCalendarActivityDiagram.puml
  docs/images/AddDeadlineLogicSequenceDiagram.png
  docs/images/AddDeadlineModelSequenceDiagram.png
  docs/images/ExportCalendarActivityDiagram.png
  src/main/java/nasa/logic/commands/ContinueCommand.java
  src/main/java/nasa/logic/commands/DoneCommand.java
  src/main/java/nasa/logic/commands/RefreshCommand.java
  src/main/java/nasa/logic/parser/NasaBookParser.java
  src/main/java/nasa/ui/ModuleListPanel.java
  src/main/java/nasa/ui/activity/DeadlineCard.java
Labels: priority.High

#287 [v1.4] Fixed minor bug and updated UG
  docs/UserGuide.adoc
  src/main/java/nasa/ui/ModuleListPanel.java
  src/main/java/nasa/ui/activity/DeadlineCard.java
Labels: priority.High

#291 [V1.4] Update DG with UML diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/AddDeadlineLogicSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ExportCalendarLogicSequenceDiagram.puml
  docs/diagrams/ExportCalendarModelSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ExportCalendarLogicSequenceDiagram.png
  docs/images/ExportCalendarModelSequenceDiagram.png
  src/main/java/nasa/ui/CalendarView.java
Labels: priority.High

#297 [V1.4] Fix schedule not updating, and schedule not setting deadline status to false.
  src/main/java/nasa/logic/commands/ContinueCommand.java
  src/main/java/nasa/logic/commands/DoneCommand.java
  src/main/java/nasa/logic/commands/EditDeadlineCommand.java
  src/main/java/nasa/logic/commands/EditEventCommand.java
  src/main/java/nasa/logic/commands/RefreshCommand.java
  src/main/java/nasa/model/Model.java
  src/main/java/nasa/model/ModelManager.java
  src/main/java/nasa/model/activity/Deadline.java
Labels: priority.High

#299 [v1.4] Updated UG
  docs/UserGuide.adoc
  docs/images/Calendar_View.png
  docs/images/Deadline-list.png
  docs/images/Event-list.png
Labels: priority.High
